// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	domain "github.com/fairyhunter13/community-waste-collection-system/internal/domain"

	uuid "github.com/google/uuid"
)

// HouseholdRepository is an autogenerated mock type for the HouseholdRepository type
type HouseholdRepository struct {
	mock.Mock
}

type HouseholdRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *HouseholdRepository) EXPECT() *HouseholdRepository_Expecter {
	return &HouseholdRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, h
func (_m *HouseholdRepository) Create(ctx context.Context, h *domain.Household) error {
	ret := _m.Called(ctx, h)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Household) error); ok {
		r0 = rf(ctx, h)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HouseholdRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type HouseholdRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - h *domain.Household
func (_e *HouseholdRepository_Expecter) Create(ctx interface{}, h interface{}) *HouseholdRepository_Create_Call {
	return &HouseholdRepository_Create_Call{Call: _e.mock.On("Create", ctx, h)}
}

func (_c *HouseholdRepository_Create_Call) Run(run func(ctx context.Context, h *domain.Household)) *HouseholdRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Household))
	})
	return _c
}

func (_c *HouseholdRepository_Create_Call) Return(_a0 error) *HouseholdRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HouseholdRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Household) error) *HouseholdRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *HouseholdRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HouseholdRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type HouseholdRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *HouseholdRepository_Expecter) Delete(ctx interface{}, id interface{}) *HouseholdRepository_Delete_Call {
	return &HouseholdRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *HouseholdRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *HouseholdRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *HouseholdRepository_Delete_Call) Return(_a0 error) *HouseholdRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HouseholdRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *HouseholdRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *HouseholdRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Household, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Household
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Household, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Household); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Household)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HouseholdRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type HouseholdRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *HouseholdRepository_Expecter) FindByID(ctx interface{}, id interface{}) *HouseholdRepository_FindByID_Call {
	return &HouseholdRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *HouseholdRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *HouseholdRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *HouseholdRepository_FindByID_Call) Return(_a0 *domain.Household, _a1 error) *HouseholdRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HouseholdRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Household, error)) *HouseholdRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, perPage
func (_m *HouseholdRepository) List(ctx context.Context, page int, perPage int) ([]*domain.Household, int, error) {
	ret := _m.Called(ctx, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Household
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.Household, int, error)); ok {
		return rf(ctx, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Household); ok {
		r0 = rf(ctx, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Household)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// HouseholdRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type HouseholdRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - perPage int
func (_e *HouseholdRepository_Expecter) List(ctx interface{}, page interface{}, perPage interface{}) *HouseholdRepository_List_Call {
	return &HouseholdRepository_List_Call{Call: _e.mock.On("List", ctx, page, perPage)}
}

func (_c *HouseholdRepository_List_Call) Run(run func(ctx context.Context, page int, perPage int)) *HouseholdRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *HouseholdRepository_List_Call) Return(_a0 []*domain.Household, _a1 int, _a2 error) *HouseholdRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *HouseholdRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]*domain.Household, int, error)) *HouseholdRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewHouseholdRepository creates a new instance of HouseholdRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHouseholdRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *HouseholdRepository {
	mock := &HouseholdRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
