// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	domain "github.com/fairyhunter13/community-waste-collection-system/internal/domain"

	uuid "github.com/google/uuid"
)

// HouseholdService is an autogenerated mock type for the HouseholdService type
type HouseholdService struct {
	mock.Mock
}

type HouseholdService_Expecter struct {
	mock *mock.Mock
}

func (_m *HouseholdService) EXPECT() *HouseholdService_Expecter {
	return &HouseholdService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, req
func (_m *HouseholdService) Create(ctx context.Context, req domain.CreateHouseholdRequest) (*domain.Household, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Household
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateHouseholdRequest) (*domain.Household, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreateHouseholdRequest) *domain.Household); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Household)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreateHouseholdRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HouseholdService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type HouseholdService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.CreateHouseholdRequest
func (_e *HouseholdService_Expecter) Create(ctx interface{}, req interface{}) *HouseholdService_Create_Call {
	return &HouseholdService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *HouseholdService_Create_Call) Run(run func(ctx context.Context, req domain.CreateHouseholdRequest)) *HouseholdService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.CreateHouseholdRequest))
	})
	return _c
}

func (_c *HouseholdService_Create_Call) Return(_a0 *domain.Household, _a1 error) *HouseholdService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HouseholdService_Create_Call) RunAndReturn(run func(context.Context, domain.CreateHouseholdRequest) (*domain.Household, error)) *HouseholdService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *HouseholdService) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HouseholdService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type HouseholdService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *HouseholdService_Expecter) Delete(ctx interface{}, id interface{}) *HouseholdService_Delete_Call {
	return &HouseholdService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *HouseholdService_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *HouseholdService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *HouseholdService_Delete_Call) Return(_a0 error) *HouseholdService_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *HouseholdService_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *HouseholdService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *HouseholdService) GetByID(ctx context.Context, id uuid.UUID) (*domain.Household, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Household
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Household, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Household); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Household)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HouseholdService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type HouseholdService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *HouseholdService_Expecter) GetByID(ctx interface{}, id interface{}) *HouseholdService_GetByID_Call {
	return &HouseholdService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *HouseholdService_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *HouseholdService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *HouseholdService_GetByID_Call) Return(_a0 *domain.Household, _a1 error) *HouseholdService_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HouseholdService_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Household, error)) *HouseholdService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, page, perPage
func (_m *HouseholdService) List(ctx context.Context, page int, perPage int) ([]*domain.Household, int, error) {
	ret := _m.Called(ctx, page, perPage)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Household
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*domain.Household, int, error)); ok {
		return rf(ctx, page, perPage)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Household); ok {
		r0 = rf(ctx, page, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Household)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int); ok {
		r1 = rf(ctx, page, perPage)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, perPage)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// HouseholdService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type HouseholdService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - perPage int
func (_e *HouseholdService_Expecter) List(ctx interface{}, page interface{}, perPage interface{}) *HouseholdService_List_Call {
	return &HouseholdService_List_Call{Call: _e.mock.On("List", ctx, page, perPage)}
}

func (_c *HouseholdService_List_Call) Run(run func(ctx context.Context, page int, perPage int)) *HouseholdService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *HouseholdService_List_Call) Return(_a0 []*domain.Household, _a1 int, _a2 error) *HouseholdService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *HouseholdService_List_Call) RunAndReturn(run func(context.Context, int, int) ([]*domain.Household, int, error)) *HouseholdService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewHouseholdService creates a new instance of HouseholdService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHouseholdService(t interface {
	mock.TestingT
	Cleanup(func())
}) *HouseholdService {
	mock := &HouseholdService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
