// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fairyhunter13/community-waste-collection-system/internal/domain"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	time "time"

	uuid "github.com/google/uuid"
)

// PaymentRepository is an autogenerated mock type for the PaymentRepository type
type PaymentRepository struct {
	mock.Mock
}

type PaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentRepository) EXPECT() *PaymentRepository_Expecter {
	return &PaymentRepository_Expecter{mock: &_m.Mock}
}

// Confirm provides a mock function with given fields: ctx, id, proofURL, paidAt
func (_m *PaymentRepository) Confirm(ctx context.Context, id uuid.UUID, proofURL string, paidAt time.Time) error {
	ret := _m.Called(ctx, id, proofURL, paidAt)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, time.Time) error); ok {
		r0 = rf(ctx, id, proofURL, paidAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PaymentRepository_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type PaymentRepository_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - proofURL string
//   - paidAt time.Time
func (_e *PaymentRepository_Expecter) Confirm(ctx interface{}, id interface{}, proofURL interface{}, paidAt interface{}) *PaymentRepository_Confirm_Call {
	return &PaymentRepository_Confirm_Call{Call: _e.mock.On("Confirm", ctx, id, proofURL, paidAt)}
}

func (_c *PaymentRepository_Confirm_Call) Run(run func(ctx context.Context, id uuid.UUID, proofURL string, paidAt time.Time)) *PaymentRepository_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(time.Time))
	})
	return _c
}

func (_c *PaymentRepository_Confirm_Call) Return(_a0 error) *PaymentRepository_Confirm_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PaymentRepository_Confirm_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, time.Time) error) *PaymentRepository_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, p
func (_m *PaymentRepository) Create(ctx context.Context, p *domain.Payment) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Payment) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PaymentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PaymentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.Payment
func (_e *PaymentRepository_Expecter) Create(ctx interface{}, p interface{}) *PaymentRepository_Create_Call {
	return &PaymentRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *PaymentRepository_Create_Call) Run(run func(ctx context.Context, p *domain.Payment)) *PaymentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Payment))
	})
	return _c
}

func (_c *PaymentRepository_Create_Call) Return(_a0 error) *PaymentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PaymentRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Payment) error) *PaymentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithTx provides a mock function with given fields: ctx, tx, p
func (_m *PaymentRepository) CreateWithTx(ctx context.Context, tx *sqlx.Tx, p *domain.Payment) error {
	ret := _m.Called(ctx, tx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, *domain.Payment) error); ok {
		r0 = rf(ctx, tx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PaymentRepository_CreateWithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithTx'
type PaymentRepository_CreateWithTx_Call struct {
	*mock.Call
}

// CreateWithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - p *domain.Payment
func (_e *PaymentRepository_Expecter) CreateWithTx(ctx interface{}, tx interface{}, p interface{}) *PaymentRepository_CreateWithTx_Call {
	return &PaymentRepository_CreateWithTx_Call{Call: _e.mock.On("CreateWithTx", ctx, tx, p)}
}

func (_c *PaymentRepository_CreateWithTx_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, p *domain.Payment)) *PaymentRepository_CreateWithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(*domain.Payment))
	})
	return _c
}

func (_c *PaymentRepository_CreateWithTx_Call) Return(_a0 error) *PaymentRepository_CreateWithTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PaymentRepository_CreateWithTx_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, *domain.Payment) error) *PaymentRepository_CreateWithTx_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *PaymentRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type PaymentRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PaymentRepository_Expecter) FindByID(ctx interface{}, id interface{}) *PaymentRepository_FindByID_Call {
	return &PaymentRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *PaymentRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PaymentRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PaymentRepository_FindByID_Call) Return(_a0 *domain.Payment, _a1 error) *PaymentRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Payment, error)) *PaymentRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// HouseholdHistory provides a mock function with given fields: ctx, householdID
func (_m *PaymentRepository) HouseholdHistory(ctx context.Context, householdID uuid.UUID) (*domain.HouseholdHistoryResult, error) {
	ret := _m.Called(ctx, householdID)

	if len(ret) == 0 {
		panic("no return value specified for HouseholdHistory")
	}

	var r0 *domain.HouseholdHistoryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.HouseholdHistoryResult, error)); ok {
		return rf(ctx, householdID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.HouseholdHistoryResult); ok {
		r0 = rf(ctx, householdID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.HouseholdHistoryResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, householdID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentRepository_HouseholdHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HouseholdHistory'
type PaymentRepository_HouseholdHistory_Call struct {
	*mock.Call
}

// HouseholdHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - householdID uuid.UUID
func (_e *PaymentRepository_Expecter) HouseholdHistory(ctx interface{}, householdID interface{}) *PaymentRepository_HouseholdHistory_Call {
	return &PaymentRepository_HouseholdHistory_Call{Call: _e.mock.On("HouseholdHistory", ctx, householdID)}
}

func (_c *PaymentRepository_HouseholdHistory_Call) Run(run func(ctx context.Context, householdID uuid.UUID)) *PaymentRepository_HouseholdHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PaymentRepository_HouseholdHistory_Call) Return(_a0 *domain.HouseholdHistoryResult, _a1 error) *PaymentRepository_HouseholdHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentRepository_HouseholdHistory_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.HouseholdHistoryResult, error)) *PaymentRepository_HouseholdHistory_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *PaymentRepository) List(ctx context.Context, filter domain.PaymentFilter) ([]*domain.Payment, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Payment
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaymentFilter) ([]*domain.Payment, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaymentFilter) []*domain.Payment); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaymentFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaymentFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PaymentRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PaymentRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.PaymentFilter
func (_e *PaymentRepository_Expecter) List(ctx interface{}, filter interface{}) *PaymentRepository_List_Call {
	return &PaymentRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *PaymentRepository_List_Call) Run(run func(ctx context.Context, filter domain.PaymentFilter)) *PaymentRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.PaymentFilter))
	})
	return _c
}

func (_c *PaymentRepository_List_Call) Return(_a0 []*domain.Payment, _a1 int, _a2 error) *PaymentRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *PaymentRepository_List_Call) RunAndReturn(run func(context.Context, domain.PaymentFilter) ([]*domain.Payment, int, error)) *PaymentRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// PaymentSummary provides a mock function with given fields: ctx
func (_m *PaymentRepository) PaymentSummary(ctx context.Context) (*domain.PaymentSummaryResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PaymentSummary")
	}

	var r0 *domain.PaymentSummaryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.PaymentSummaryResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.PaymentSummaryResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentSummaryResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentRepository_PaymentSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PaymentSummary'
type PaymentRepository_PaymentSummary_Call struct {
	*mock.Call
}

// PaymentSummary is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PaymentRepository_Expecter) PaymentSummary(ctx interface{}) *PaymentRepository_PaymentSummary_Call {
	return &PaymentRepository_PaymentSummary_Call{Call: _e.mock.On("PaymentSummary", ctx)}
}

func (_c *PaymentRepository_PaymentSummary_Call) Run(run func(ctx context.Context)) *PaymentRepository_PaymentSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PaymentRepository_PaymentSummary_Call) Return(_a0 *domain.PaymentSummaryResult, _a1 error) *PaymentRepository_PaymentSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentRepository_PaymentSummary_Call) RunAndReturn(run func(context.Context) (*domain.PaymentSummaryResult, error)) *PaymentRepository_PaymentSummary_Call {
	_c.Call.Return(run)
	return _c
}

// WasteSummary provides a mock function with given fields: ctx
func (_m *PaymentRepository) WasteSummary(ctx context.Context) ([]domain.WasteTypeSummary, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WasteSummary")
	}

	var r0 []domain.WasteTypeSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.WasteTypeSummary, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.WasteTypeSummary); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WasteTypeSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentRepository_WasteSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WasteSummary'
type PaymentRepository_WasteSummary_Call struct {
	*mock.Call
}

// WasteSummary is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PaymentRepository_Expecter) WasteSummary(ctx interface{}) *PaymentRepository_WasteSummary_Call {
	return &PaymentRepository_WasteSummary_Call{Call: _e.mock.On("WasteSummary", ctx)}
}

func (_c *PaymentRepository_WasteSummary_Call) Run(run func(ctx context.Context)) *PaymentRepository_WasteSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PaymentRepository_WasteSummary_Call) Return(_a0 []domain.WasteTypeSummary, _a1 error) *PaymentRepository_WasteSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentRepository_WasteSummary_Call) RunAndReturn(run func(context.Context) ([]domain.WasteTypeSummary, error)) *PaymentRepository_WasteSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentRepository creates a new instance of PaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRepository {
	mock := &PaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
