// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	domain "github.com/fairyhunter13/community-waste-collection-system/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

type PaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *PaymentService) EXPECT() *PaymentService_Expecter {
	return &PaymentService_Expecter{mock: &_m.Mock}
}

// Confirm provides a mock function with given fields: ctx, id, file, size, contentType
func (_m *PaymentService) Confirm(ctx context.Context, id uuid.UUID, file io.Reader, size int64, contentType string) (*domain.Payment, error) {
	ret := _m.Called(ctx, id, file, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, io.Reader, int64, string) (*domain.Payment, error)); ok {
		return rf(ctx, id, file, size, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, io.Reader, int64, string) *domain.Payment); ok {
		r0 = rf(ctx, id, file, size, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, io.Reader, int64, string) error); ok {
		r1 = rf(ctx, id, file, size, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentService_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type PaymentService_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - file io.Reader
//   - size int64
//   - contentType string
func (_e *PaymentService_Expecter) Confirm(ctx interface{}, id interface{}, file interface{}, size interface{}, contentType interface{}) *PaymentService_Confirm_Call {
	return &PaymentService_Confirm_Call{Call: _e.mock.On("Confirm", ctx, id, file, size, contentType)}
}

func (_c *PaymentService_Confirm_Call) Run(run func(ctx context.Context, id uuid.UUID, file io.Reader, size int64, contentType string)) *PaymentService_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(io.Reader), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *PaymentService_Confirm_Call) Return(_a0 *domain.Payment, _a1 error) *PaymentService_Confirm_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentService_Confirm_Call) RunAndReturn(run func(context.Context, uuid.UUID, io.Reader, int64, string) (*domain.Payment, error)) *PaymentService_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, req
func (_m *PaymentService) Create(ctx context.Context, req domain.CreatePaymentRequest) (*domain.Payment, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreatePaymentRequest) (*domain.Payment, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreatePaymentRequest) *domain.Payment); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreatePaymentRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PaymentService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PaymentService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.CreatePaymentRequest
func (_e *PaymentService_Expecter) Create(ctx interface{}, req interface{}) *PaymentService_Create_Call {
	return &PaymentService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *PaymentService_Create_Call) Run(run func(ctx context.Context, req domain.CreatePaymentRequest)) *PaymentService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.CreatePaymentRequest))
	})
	return _c
}

func (_c *PaymentService_Create_Call) Return(_a0 *domain.Payment, _a1 error) *PaymentService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PaymentService_Create_Call) RunAndReturn(run func(context.Context, domain.CreatePaymentRequest) (*domain.Payment, error)) *PaymentService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *PaymentService) List(ctx context.Context, filter domain.PaymentFilter) ([]*domain.Payment, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Payment
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaymentFilter) ([]*domain.Payment, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PaymentFilter) []*domain.Payment); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PaymentFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PaymentFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PaymentService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PaymentService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.PaymentFilter
func (_e *PaymentService_Expecter) List(ctx interface{}, filter interface{}) *PaymentService_List_Call {
	return &PaymentService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *PaymentService_List_Call) Run(run func(ctx context.Context, filter domain.PaymentFilter)) *PaymentService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.PaymentFilter))
	})
	return _c
}

func (_c *PaymentService_List_Call) Return(_a0 []*domain.Payment, _a1 int, _a2 error) *PaymentService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *PaymentService_List_Call) RunAndReturn(run func(context.Context, domain.PaymentFilter) ([]*domain.Payment, int, error)) *PaymentService_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
