// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fairyhunter13/community-waste-collection-system/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PickupService is an autogenerated mock type for the PickupService type
type PickupService struct {
	mock.Mock
}

type PickupService_Expecter struct {
	mock *mock.Mock
}

func (_m *PickupService) EXPECT() *PickupService_Expecter {
	return &PickupService_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, id
func (_m *PickupService) Cancel(ctx context.Context, id uuid.UUID) (*domain.WastePickup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 *domain.WastePickup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.WastePickup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.WastePickup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WastePickup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PickupService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type PickupService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PickupService_Expecter) Cancel(ctx interface{}, id interface{}) *PickupService_Cancel_Call {
	return &PickupService_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id)}
}

func (_c *PickupService_Cancel_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PickupService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PickupService_Cancel_Call) Return(_a0 *domain.WastePickup, _a1 error) *PickupService_Cancel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PickupService_Cancel_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.WastePickup, error)) *PickupService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function with given fields: ctx, id
func (_m *PickupService) Complete(ctx context.Context, id uuid.UUID) (*domain.WastePickup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 *domain.WastePickup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.WastePickup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.WastePickup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WastePickup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PickupService_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type PickupService_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PickupService_Expecter) Complete(ctx interface{}, id interface{}) *PickupService_Complete_Call {
	return &PickupService_Complete_Call{Call: _e.mock.On("Complete", ctx, id)}
}

func (_c *PickupService_Complete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PickupService_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PickupService_Complete_Call) Return(_a0 *domain.WastePickup, _a1 error) *PickupService_Complete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PickupService_Complete_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.WastePickup, error)) *PickupService_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, req
func (_m *PickupService) Create(ctx context.Context, req domain.CreatePickupRequest) (*domain.WastePickup, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.WastePickup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreatePickupRequest) (*domain.WastePickup, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.CreatePickupRequest) *domain.WastePickup); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WastePickup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.CreatePickupRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PickupService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PickupService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - req domain.CreatePickupRequest
func (_e *PickupService_Expecter) Create(ctx interface{}, req interface{}) *PickupService_Create_Call {
	return &PickupService_Create_Call{Call: _e.mock.On("Create", ctx, req)}
}

func (_c *PickupService_Create_Call) Run(run func(ctx context.Context, req domain.CreatePickupRequest)) *PickupService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.CreatePickupRequest))
	})
	return _c
}

func (_c *PickupService_Create_Call) Return(_a0 *domain.WastePickup, _a1 error) *PickupService_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PickupService_Create_Call) RunAndReturn(run func(context.Context, domain.CreatePickupRequest) (*domain.WastePickup, error)) *PickupService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *PickupService) List(ctx context.Context, filter domain.PickupFilter) ([]*domain.WastePickup, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.WastePickup
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PickupFilter) ([]*domain.WastePickup, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PickupFilter) []*domain.WastePickup); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.WastePickup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PickupFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PickupFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PickupService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PickupService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.PickupFilter
func (_e *PickupService_Expecter) List(ctx interface{}, filter interface{}) *PickupService_List_Call {
	return &PickupService_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *PickupService_List_Call) Run(run func(ctx context.Context, filter domain.PickupFilter)) *PickupService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.PickupFilter))
	})
	return _c
}

func (_c *PickupService_List_Call) Return(_a0 []*domain.WastePickup, _a1 int, _a2 error) *PickupService_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *PickupService_List_Call) RunAndReturn(run func(context.Context, domain.PickupFilter) ([]*domain.WastePickup, int, error)) *PickupService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Schedule provides a mock function with given fields: ctx, id, req
func (_m *PickupService) Schedule(ctx context.Context, id uuid.UUID, req domain.SchedulePickupRequest) (*domain.WastePickup, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Schedule")
	}

	var r0 *domain.WastePickup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.SchedulePickupRequest) (*domain.WastePickup, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.SchedulePickupRequest) *domain.WastePickup); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WastePickup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, domain.SchedulePickupRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PickupService_Schedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schedule'
type PickupService_Schedule_Call struct {
	*mock.Call
}

// Schedule is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - req domain.SchedulePickupRequest
func (_e *PickupService_Expecter) Schedule(ctx interface{}, id interface{}, req interface{}) *PickupService_Schedule_Call {
	return &PickupService_Schedule_Call{Call: _e.mock.On("Schedule", ctx, id, req)}
}

func (_c *PickupService_Schedule_Call) Run(run func(ctx context.Context, id uuid.UUID, req domain.SchedulePickupRequest)) *PickupService_Schedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.SchedulePickupRequest))
	})
	return _c
}

func (_c *PickupService_Schedule_Call) Return(_a0 *domain.WastePickup, _a1 error) *PickupService_Schedule_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PickupService_Schedule_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.SchedulePickupRequest) (*domain.WastePickup, error)) *PickupService_Schedule_Call {
	_c.Call.Return(run)
	return _c
}

// NewPickupService creates a new instance of PickupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPickupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PickupService {
	mock := &PickupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
