// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fairyhunter13/community-waste-collection-system/internal/domain"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"

	time "time"

	uuid "github.com/google/uuid"
)

// PickupRepository is an autogenerated mock type for the PickupRepository type
type PickupRepository struct {
	mock.Mock
}

type PickupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PickupRepository) EXPECT() *PickupRepository_Expecter {
	return &PickupRepository_Expecter{mock: &_m.Mock}
}

// BulkCancel provides a mock function with given fields: ctx, ids
func (_m *PickupRepository) BulkCancel(ctx context.Context, ids []uuid.UUID) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkCancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PickupRepository_BulkCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCancel'
type PickupRepository_BulkCancel_Call struct {
	*mock.Call
}

// BulkCancel is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *PickupRepository_Expecter) BulkCancel(ctx interface{}, ids interface{}) *PickupRepository_BulkCancel_Call {
	return &PickupRepository_BulkCancel_Call{Call: _e.mock.On("BulkCancel", ctx, ids)}
}

func (_c *PickupRepository_BulkCancel_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *PickupRepository_BulkCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *PickupRepository_BulkCancel_Call) Return(_a0 error) *PickupRepository_BulkCancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PickupRepository_BulkCancel_Call) RunAndReturn(run func(context.Context, []uuid.UUID) error) *PickupRepository_BulkCancel_Call {
	_c.Call.Return(run)
	return _c
}

// CancelIfCancellable provides a mock function with given fields: ctx, id
func (_m *PickupRepository) CancelIfCancellable(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelIfCancellable")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PickupRepository_CancelIfCancellable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelIfCancellable'
type PickupRepository_CancelIfCancellable_Call struct {
	*mock.Call
}

// CancelIfCancellable is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PickupRepository_Expecter) CancelIfCancellable(ctx interface{}, id interface{}) *PickupRepository_CancelIfCancellable_Call {
	return &PickupRepository_CancelIfCancellable_Call{Call: _e.mock.On("CancelIfCancellable", ctx, id)}
}

func (_c *PickupRepository_CancelIfCancellable_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PickupRepository_CancelIfCancellable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PickupRepository_CancelIfCancellable_Call) Return(_a0 bool, _a1 error) *PickupRepository_CancelIfCancellable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PickupRepository_CancelIfCancellable_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *PickupRepository_CancelIfCancellable_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, p
func (_m *PickupRepository) Create(ctx context.Context, p *domain.WastePickup) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.WastePickup) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PickupRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type PickupRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.WastePickup
func (_e *PickupRepository_Expecter) Create(ctx interface{}, p interface{}) *PickupRepository_Create_Call {
	return &PickupRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *PickupRepository_Create_Call) Run(run func(ctx context.Context, p *domain.WastePickup)) *PickupRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.WastePickup))
	})
	return _c
}

func (_c *PickupRepository_Create_Call) Return(_a0 error) *PickupRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PickupRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.WastePickup) error) *PickupRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *PickupRepository) FindByID(ctx context.Context, id uuid.UUID) (*domain.WastePickup, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.WastePickup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.WastePickup, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.WastePickup); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WastePickup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PickupRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type PickupRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *PickupRepository_Expecter) FindByID(ctx interface{}, id interface{}) *PickupRepository_FindByID_Call {
	return &PickupRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *PickupRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *PickupRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PickupRepository_FindByID_Call) Return(_a0 *domain.WastePickup, _a1 error) *PickupRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PickupRepository_FindByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.WastePickup, error)) *PickupRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindExpiredOrganic provides a mock function with given fields: ctx, before
func (_m *PickupRepository) FindExpiredOrganic(ctx context.Context, before time.Time) ([]*domain.WastePickup, error) {
	ret := _m.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for FindExpiredOrganic")
	}

	var r0 []*domain.WastePickup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]*domain.WastePickup, error)); ok {
		return rf(ctx, before)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []*domain.WastePickup); ok {
		r0 = rf(ctx, before)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.WastePickup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, before)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PickupRepository_FindExpiredOrganic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindExpiredOrganic'
type PickupRepository_FindExpiredOrganic_Call struct {
	*mock.Call
}

// FindExpiredOrganic is a helper method to define mock.On call
//   - ctx context.Context
//   - before time.Time
func (_e *PickupRepository_Expecter) FindExpiredOrganic(ctx interface{}, before interface{}) *PickupRepository_FindExpiredOrganic_Call {
	return &PickupRepository_FindExpiredOrganic_Call{Call: _e.mock.On("FindExpiredOrganic", ctx, before)}
}

func (_c *PickupRepository_FindExpiredOrganic_Call) Run(run func(ctx context.Context, before time.Time)) *PickupRepository_FindExpiredOrganic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *PickupRepository_FindExpiredOrganic_Call) Return(_a0 []*domain.WastePickup, _a1 error) *PickupRepository_FindExpiredOrganic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PickupRepository_FindExpiredOrganic_Call) RunAndReturn(run func(context.Context, time.Time) ([]*domain.WastePickup, error)) *PickupRepository_FindExpiredOrganic_Call {
	_c.Call.Return(run)
	return _c
}

// HasPendingPaymentForHousehold provides a mock function with given fields: ctx, householdID
func (_m *PickupRepository) HasPendingPaymentForHousehold(ctx context.Context, householdID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, householdID)

	if len(ret) == 0 {
		panic("no return value specified for HasPendingPaymentForHousehold")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, householdID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, householdID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, householdID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PickupRepository_HasPendingPaymentForHousehold_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasPendingPaymentForHousehold'
type PickupRepository_HasPendingPaymentForHousehold_Call struct {
	*mock.Call
}

// HasPendingPaymentForHousehold is a helper method to define mock.On call
//   - ctx context.Context
//   - householdID uuid.UUID
func (_e *PickupRepository_Expecter) HasPendingPaymentForHousehold(ctx interface{}, householdID interface{}) *PickupRepository_HasPendingPaymentForHousehold_Call {
	return &PickupRepository_HasPendingPaymentForHousehold_Call{Call: _e.mock.On("HasPendingPaymentForHousehold", ctx, householdID)}
}

func (_c *PickupRepository_HasPendingPaymentForHousehold_Call) Run(run func(ctx context.Context, householdID uuid.UUID)) *PickupRepository_HasPendingPaymentForHousehold_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *PickupRepository_HasPendingPaymentForHousehold_Call) Return(_a0 bool, _a1 error) *PickupRepository_HasPendingPaymentForHousehold_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PickupRepository_HasPendingPaymentForHousehold_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *PickupRepository_HasPendingPaymentForHousehold_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *PickupRepository) List(ctx context.Context, filter domain.PickupFilter) ([]*domain.WastePickup, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.WastePickup
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.PickupFilter) ([]*domain.WastePickup, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.PickupFilter) []*domain.WastePickup); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.WastePickup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.PickupFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, domain.PickupFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// PickupRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type PickupRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.PickupFilter
func (_e *PickupRepository_Expecter) List(ctx interface{}, filter interface{}) *PickupRepository_List_Call {
	return &PickupRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *PickupRepository_List_Call) Run(run func(ctx context.Context, filter domain.PickupFilter)) *PickupRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.PickupFilter))
	})
	return _c
}

func (_c *PickupRepository_List_Call) Return(_a0 []*domain.WastePickup, _a1 int, _a2 error) *PickupRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *PickupRepository_List_Call) RunAndReturn(run func(context.Context, domain.PickupFilter) ([]*domain.WastePickup, int, error)) *PickupRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Schedule provides a mock function with given fields: ctx, id, date
func (_m *PickupRepository) Schedule(ctx context.Context, id uuid.UUID, date time.Time) error {
	ret := _m.Called(ctx, id, date)

	if len(ret) == 0 {
		panic("no return value specified for Schedule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, id, date)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PickupRepository_Schedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schedule'
type PickupRepository_Schedule_Call struct {
	*mock.Call
}

// Schedule is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - date time.Time
func (_e *PickupRepository_Expecter) Schedule(ctx interface{}, id interface{}, date interface{}) *PickupRepository_Schedule_Call {
	return &PickupRepository_Schedule_Call{Call: _e.mock.On("Schedule", ctx, id, date)}
}

func (_c *PickupRepository_Schedule_Call) Run(run func(ctx context.Context, id uuid.UUID, date time.Time)) *PickupRepository_Schedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *PickupRepository_Schedule_Call) Return(_a0 error) *PickupRepository_Schedule_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PickupRepository_Schedule_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *PickupRepository_Schedule_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, id, status, tx
func (_m *PickupRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status domain.PickupStatus, tx ...*sqlx.Tx) error {
	_va := make([]interface{}, len(tx))
	for _i := range tx {
		_va[_i] = tx[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, id, status)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.PickupStatus, ...*sqlx.Tx) error); ok {
		r0 = rf(ctx, id, status, tx...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PickupRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type PickupRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status domain.PickupStatus
//   - tx ...*sqlx.Tx
func (_e *PickupRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}, tx ...interface{}) *PickupRepository_UpdateStatus_Call {
	return &PickupRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus",
		append([]interface{}{ctx, id, status}, tx...)...)}
}

func (_c *PickupRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status domain.PickupStatus, tx ...*sqlx.Tx)) *PickupRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*sqlx.Tx, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(*sqlx.Tx)
			}
		}
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.PickupStatus), variadicArgs...)
	})
	return _c
}

func (_c *PickupRepository_UpdateStatus_Call) Return(_a0 error) *PickupRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PickupRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.PickupStatus, ...*sqlx.Tx) error) *PickupRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewPickupRepository creates a new instance of PickupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPickupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PickupRepository {
	mock := &PickupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
