// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/fairyhunter13/community-waste-collection-system/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ReportService is an autogenerated mock type for the ReportService type
type ReportService struct {
	mock.Mock
}

type ReportService_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportService) EXPECT() *ReportService_Expecter {
	return &ReportService_Expecter{mock: &_m.Mock}
}

// HouseholdHistory provides a mock function with given fields: ctx, id
func (_m *ReportService) HouseholdHistory(ctx context.Context, id uuid.UUID) (*domain.HouseholdHistoryResult, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for HouseholdHistory")
	}

	var r0 *domain.HouseholdHistoryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.HouseholdHistoryResult, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.HouseholdHistoryResult); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.HouseholdHistoryResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_HouseholdHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HouseholdHistory'
type ReportService_HouseholdHistory_Call struct {
	*mock.Call
}

// HouseholdHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ReportService_Expecter) HouseholdHistory(ctx interface{}, id interface{}) *ReportService_HouseholdHistory_Call {
	return &ReportService_HouseholdHistory_Call{Call: _e.mock.On("HouseholdHistory", ctx, id)}
}

func (_c *ReportService_HouseholdHistory_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ReportService_HouseholdHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ReportService_HouseholdHistory_Call) Return(_a0 *domain.HouseholdHistoryResult, _a1 error) *ReportService_HouseholdHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_HouseholdHistory_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.HouseholdHistoryResult, error)) *ReportService_HouseholdHistory_Call {
	_c.Call.Return(run)
	return _c
}

// PaymentSummary provides a mock function with given fields: ctx
func (_m *ReportService) PaymentSummary(ctx context.Context) (*domain.PaymentSummaryResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PaymentSummary")
	}

	var r0 *domain.PaymentSummaryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.PaymentSummaryResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.PaymentSummaryResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PaymentSummaryResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_PaymentSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PaymentSummary'
type ReportService_PaymentSummary_Call struct {
	*mock.Call
}

// PaymentSummary is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReportService_Expecter) PaymentSummary(ctx interface{}) *ReportService_PaymentSummary_Call {
	return &ReportService_PaymentSummary_Call{Call: _e.mock.On("PaymentSummary", ctx)}
}

func (_c *ReportService_PaymentSummary_Call) Run(run func(ctx context.Context)) *ReportService_PaymentSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReportService_PaymentSummary_Call) Return(_a0 *domain.PaymentSummaryResult, _a1 error) *ReportService_PaymentSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_PaymentSummary_Call) RunAndReturn(run func(context.Context) (*domain.PaymentSummaryResult, error)) *ReportService_PaymentSummary_Call {
	_c.Call.Return(run)
	return _c
}

// WasteSummary provides a mock function with given fields: ctx
func (_m *ReportService) WasteSummary(ctx context.Context) ([]domain.WasteTypeSummary, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WasteSummary")
	}

	var r0 []domain.WasteTypeSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.WasteTypeSummary, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.WasteTypeSummary); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WasteTypeSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportService_WasteSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WasteSummary'
type ReportService_WasteSummary_Call struct {
	*mock.Call
}

// WasteSummary is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReportService_Expecter) WasteSummary(ctx interface{}) *ReportService_WasteSummary_Call {
	return &ReportService_WasteSummary_Call{Call: _e.mock.On("WasteSummary", ctx)}
}

func (_c *ReportService_WasteSummary_Call) Run(run func(ctx context.Context)) *ReportService_WasteSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReportService_WasteSummary_Call) Return(_a0 []domain.WasteTypeSummary, _a1 error) *ReportService_WasteSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportService_WasteSummary_Call) RunAndReturn(run func(context.Context) ([]domain.WasteTypeSummary, error)) *ReportService_WasteSummary_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportService creates a new instance of ReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportService {
	mock := &ReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
