// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// StorageService is an autogenerated mock type for the StorageService type
type StorageService struct {
	mock.Mock
}

type StorageService_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageService) EXPECT() *StorageService_Expecter {
	return &StorageService_Expecter{mock: &_m.Mock}
}

// Upload provides a mock function with given fields: ctx, key, r, size, contentType
func (_m *StorageService) Upload(ctx context.Context, key string, r io.Reader, size int64, contentType string) (string, error) {
	ret := _m.Called(ctx, key, r, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) (string, error)); ok {
		return rf(ctx, key, r, size, contentType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) string); ok {
		r0 = rf(ctx, key, r, size, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r1 = rf(ctx, key, r, size, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageService_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type StorageService_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - r io.Reader
//   - size int64
//   - contentType string
func (_e *StorageService_Expecter) Upload(ctx interface{}, key interface{}, r interface{}, size interface{}, contentType interface{}) *StorageService_Upload_Call {
	return &StorageService_Upload_Call{Call: _e.mock.On("Upload", ctx, key, r, size, contentType)}
}

func (_c *StorageService_Upload_Call) Run(run func(ctx context.Context, key string, r io.Reader, size int64, contentType string)) *StorageService_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *StorageService_Upload_Call) Return(url string, err error) *StorageService_Upload_Call {
	_c.Call.Return(url, err)
	return _c
}

func (_c *StorageService_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader, int64, string) (string, error)) *StorageService_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageService creates a new instance of StorageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageService {
	mock := &StorageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
