apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: prometheus
        tags:
          - key: pickup.type
          - key: db.sql.table
          - key: db.operation
