version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 5
    assignees:
      - fairyhunter13
    labels:
      - dependencies
      - go
    commit-message:
      prefix: "chore(deps)"
    groups:
      aws-sdk:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
      opentelemetry:
        patterns:
          - "go.opentelemetry.io/*"
      testcontainers:
        patterns:
          - "github.com/testcontainers/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 5
    assignees:
      - fairyhunter13
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "chore(deps)"
